language: cpp
compiler:
  - gcc
# - clang
before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y libxpm-dev libfreetype6-dev libxcomposite-dev libsm-dev libxext-dev libxft-dev libxmu-dev libbsd-dev
script: make
